config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :books
  get 'welcome/index'
  get 'novels/index'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_title, :author, :genre, :reading_level, :number_of_pages, :copyrighted, :publisher, :summary)
    end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
before_action :novel_length, only: [:index]
  def index
  	@books = Book.all
  end

  def novel_length
  	@books = Book.all
    @novel_length_books = []

    @books.each do |book|
         if book.number_of_pages.to_i >= 240
             @novel_length_books.push(book)
         end
     end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :book_title %>
    <%= f.input :author %>
    <%= f.input :genre %>
    <%= f.input :reading_level %>
    <%= f.input :number_of_pages %>
    <%= f.input :copyrighted %>
    <%= f.input :publisher %>
    <%= f.input :summary %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Books</h1>

<div class="row">
   <% @books.each do |book| %>
   <div class="col-md-3">
       <div class="well center-it">
           <h2><%= link_to book.book_title, book %></h2>
           <p><em><%= book.author %></em></p>
           <p><%= truncate(book.summary, :length => 100) %><%= link_to "Read More", book %></p>
               <a href="#" data-toggle="modal" data-target="#myModal_<%= book.id %>">
                   <span class="glyphicon glyphicon-book"> Details </span>
               </a>
           </p>
       </div>
   </div>

    <div id="myModal_<%= book.id %>" class="modal fade" tabindex="-1" role="dialog">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title"><%= link_to book.book_title, book %></h4>
         </div>
         <div class="modal-body">
          <p>Author: <%= book.author %></p>
          <p>Genre: <%= book.genre %></p>
          <p>Reading Level: <%= book.reading_level %></p>
          <p><%= book.number_of_pages %> pages</p>
          <p><%= book.publisher %>, <%= book.copyrighted %></p>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
           <button type="button" class="btn btn-primary"><%= link_to "See Full Page", book %></button>
         </div>
       </div><!-- /.modal-content -->
     </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

   <% end %>
</div>
<br>
<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @book.book_title %></h1>

<h2>By <%= @book.author %></h2>
<br>
<br>
<p class="well center-it">
  <strong>Summary:</strong>
  <%= @book.summary %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Reading level:</strong>
  <%= @book.reading_level %>
</p>

<p>
  <strong>Number of pages:</strong>
  <%= @book.number_of_pages %>
</p>

<p>
  <strong>Published:</strong>
  <%= @book.publisher %>: <%= @book.copyrighted %>
</p>



<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'All Books', books_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">My Library</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Books", books_path %></li>
        <li><%= link_to "Novels", novels_index_path %></li>     
      </ul>   
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyLibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div class="container" padding-top: 70px>
<%= yield %>
</div>
</body>
</html>

app/views/novels/index.html.erb
<h1>Novels</h1>

<div class="row">
   <% @novel_length_books.each do |book| %>
   <div class="col-md-3">
       <div class="well center-it">
           <h2><%= link_to book.book_title, book %></h2>
           <p><em><%= book.author %></em></p>
           <p><%= truncate(book.summary, :length => 100) %><%= link_to "Read More", book %></p>
               <a href="#" data-toggle="modal" data-target="#myModal_<%= book.id %>">
                   <span class="glyphicon glyphicon-book"> Details </span>
               </a>
           </p>
       </div>
   </div>

    <div id="myModal_<%= book.id %>" class="modal fade" tabindex="-1" role="dialog">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title"><%= link_to book.book_title, book %></h4>
         </div>
         <div class="modal-body">
          <p>Author: <%= book.author %></p>
          <p>Genre: <%= book.genre %></p>
          <p>Reading Level: <%= book.reading_level %></p>
          <p><%= book.number_of_pages %> pages</p>
          <p><%= book.publisher %>, <%= book.copyrighted %></p>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
           <button type="button" class="btn btn-primary"><%= link_to "See Full Page", book %></button>
         </div>
       </div><!-- /.modal-content -->
     </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

   <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to MyLibrary!</h1>
<h4>Please, use the navbar and explore!</h4>
<img src="http://pre07.deviantart.net/4570/th/pre/i/2011/273/d/e/antique_books_4_by_stock_by_casey-d4bfc4x.jpg" width=100%>